default_connection_name = "advanced-data-engineering-snowflake"

[connections.\advanced-data-engineering-snowflake]
account = "BMXVMYT-NWB08201"
user="AMAN"
password="Snowflakeisneeded@007"
warehouse="COMPUTE_WH"
database="LOAD_DATA"
schema="PUBLIC"
role="ACCOUNTADMIN"